on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

  workflow_dispatch:

jobs:
        
  ubuntu2204msbuild:
    name: ubuntu2204msbuild
    runs-on: ubuntu-22.04

    steps:
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt install ca-certificates gnupg
        sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt install mono-complete

     # Checkout, configure and build
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Checkout configure and build
      run: |
        nuget restore
        msbuild /t:Build /p:Configuration=Debug /p:Platform="Any CPU"
