on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'


  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: |
        apt-get update
        apt-get install -y sudo        
        sudo apt-get update
        # Install mono and msbuild
        sudo apt install ca-certificates gnupg
        sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt install mono-complete
        
    - name: Checkout configure and build
      run: |
        make && make run

        
